### ISSUE TITLE
Failed to start new video session.

### ISSUE THREAD

**Issue by FrankGNL** [kodosexe/F1Hub#2]
When trying to plat a stream with mpg, get this error:
Failed to start new video session. Please open an issue on the GitHub repo as soon as possible, including your Operating System. Thanks!

MPV:
xxx-MacBook:f1hub xxx$ mpv --version
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jan 16 08:17:56 GMT 2021
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.2

OS:
Big Sur Intel 11.2.3

**Comment by kodosexe** [comment]
Hey, thanks for submitting.

The way to start mpv in a seperate Terminal tab is different for Linux, Windows and MacOS.
I'm personally running Linux, and I will have an opportunity to test on Windows soon. Unfortunately, macOS is difficult for me to support, because there is almost no way to test it.

If you have programming knowledge, I would much appreciate if you could take a look at the startStream file and see whether the code to start a new MacOS session in startMacOSStream() seems right.

If not, I may be able to figure something out in the next few days.

**Comment by FrankGNL** [comment]
I'm not a python guru,
but what I found out is that is is failing line number 405 of main.py

```
If I alter it like this:
                                try:
                                    #subprocess.call(["gnome-terminal", "-x", "mpv", "--border=no", streamUrl])
                                    subprocess.call(['/usr/local/bin/mpv', streamUrl])
                                except:
                                    print("Failed to start new video session. Please open an issue on the GitHub repo as soon as possible, including your Operating System. Thanks!")
                            except:
                                print("Failed to get Playable Link... are you logged in?")
```

It is working, for mpg I needed to use the full path, otherwise it tried to open mpv from the root folder of the repo

**Comment by kodosexe** [comment]
Interesting, I'll be committing a fix later today. Thanks a lot!

**Comment by FrankGNL** [comment]
Thx, happy to test the fix!!

**Comment by kodosexe** [comment]
Just released version pre-0.8, which should fix the issue.
You were running an older version, I have slightly reworked the stream start system since then, but I have implemented the fix you suggested.
Please try out the new version to make sure it works now.

**Comment by FrankGNL** [comment]
Still not working, tested it with a live stream that is running now. It looks like it is not even using the startStream.py
From the main.py it is using subprocess.call

**Comment by kodosexe** [comment]
My bad, only changed the code on one part of the code...
I just re-released the update.
Thanks!

**Comment by FrankGNL** [comment]
It is working, thx!!

**Comment by kodosexe** [comment]
Great!
Closing this now.
Thanks for the help!
